-- ZA class file

ZA = {}

ZA.vars = {
	[1] = "", 
	[2] = "",
	[3] = "",  
	[4] = "\n/use Element-Infused Rocket Helmet",
	[5] = "\n/use Goren \"Log\" Roller", 
	[6] = "", 
	[7] = "",
	[8] = "",
	[9] = "",
	[10] = "",
	[11] = "",
	[12] = "",
	[13] = "",
	[14] = "",
	[15] = "",
	[16] = "",
	[17] = "",
	[18] = "",
	[19] = "",
	[20] = "",
	[21] = "Loot-A-Rang",
	[22] = "Photo B.O.M.B.",
	[23] = "Citizens Brigade Whistle",
	[24] = "Signature Ability",
	[25] = "",
	[26] = "Covenant Ability",
	[27] = "",
	[28] = "\n/use [mod]item:177278",
	[29] = "[@mouseover,exists,nodead][@cursor]13",
	[30] = "",
	[31] = "",
	[32] = "Horde Flag of Victory",
	[33] = "Firefury Totem",
	[34] = "Darkspear Pride",
	[35] = "Everlasting Horde Firework",
	[36] = "Orgrimmar Interceptor",
	[37] = "",
	[38] = "[@mouseover,exists,nodead][]Command Demon",
	[39] = "",
	[40] = "[@focus,harm,nodead]Command Demon;",
	[41] = "@party",
	[42] = "",
	[43] = "",
	[44] = "/use [@mouseover,exists,nodead][@cursor]Garrison Ability",
	[45] = "\n/use Moroes' Famous Polish",
	[46] = "\n/use Skyfury",
	[47] = "",
	[48] = "Tipipants",
	[49] = "",
	[50] = "\n/use Orb of Deception",
	[51] = "",
	[52] = "\n/use Honorable Pennant",
	[53] = {"Iridal, the Earth's Master", "Dreambinder, Loom of the Great Cycle", "Djaruun, Pillar of the Elder Flame","Cruel Dreamcarver","Kharnalex, The First Light"},
	[54] = "",
	[55] = "",
	[56] = "",
	[57] = "",
	[58] = {},
	[59] = {},
	[60] = {},
	[61] = {},
	[62] = "\n/use [help,nocombat]Swapblaster"
}

ZA.cov = {
	[0] = "Uninitiated",
	[1] = "Kyrian",
	[2] = "Venthyr",
	[3] = "Night Fae",
	[4] = "Necrolord",
	[5] = "Mawsworn",
	[6] = "Enlightened",
}

-- covTable[cov[slBP][class]]
ZA.covTable = {
	["Uninitiated"] = {
		["SHAMAN"] = "",
		["MAGE"] = "",
		["WARLOCK"] = "",
		["MONK"] = "",
		["PALADIN"] = "",
		["HUNTER"] = "",
		["ROGUE"] = "",
		["PRIEST"] = "",
		["DEATHKNIGHT"] = "",
		["WARRIOR"] = "",
		["DRUID"] = "",
		["DEMONHUNTER"] = "",
		["EVOKER"] = "",
	},
	["Kyrian"] = {
		["SHAMAN"] = "Vesper Totem",
		["MAGE"] = "Radiant Spark",
		["WARLOCK"] = "Scouring Tithe",
		["MONK"] = "Weapons of Order",
		["PALADIN"] = "Divine Toll",
		["HUNTER"] = "Resonating Arrow",
		["ROGUE"] = "Echoing Reprimand",
		["PRIEST"] = "Boon of the Ascended",
		["DEATHKNIGHT"] = "Shackle the Unworthy",
		["WARRIOR"] = "Spear of Bastion",
		["DRUID"] = "Kindred Spirits",
		["DEMONHUNTER"] = "Elysian Decree",
		["EVOKER"] = "Boon of the Covenants",
	},
	["Necrolord"] = {
		["SHAMAN"] = "Primordial Wave",
		["MAGE"] = "Deathborne",
		["WARLOCK"] = "Decimating Bolt",
		["MONK"] = "Bonedust Brew",
		["PALADIN"] = "Vanquisher's Hammer",
		["HUNTER"] = "Death Chakram",
		["ROGUE"] = "Serrated Bone Spike",
		["PRIEST"] = "Unholy Nova",
		["DEATHKNIGHT"] = "Abomination Limb",
		["WARRIOR"] = "Conqueror's Banner",
		["DRUID"] = "Adaptive Swarm(Necrolord)",
		["DEMONHUNTER"] = "Fodder to the Flame",
		["EVOKER"] = "Boon of the Covenants",
	},
	["Night Fae"] = {
		["SHAMAN"] = "Fae Transfusion",
		["MAGE"] = "Shifting Power",
		["WARLOCK"] = "Soul Rot",
		["MONK"] = "Faeline Stomp",
		["PALADIN"] = "Blessing of Summer",
		["HUNTER"] = "Wild Spirits",
		["ROGUE"] = "Sepsis",
		["PRIEST"] = "Fae Guardians",
		["DEATHKNIGHT"] = "Death's Due",
		["WARRIOR"] = "Ancient Aftershock",
		["DRUID"] = "Convoke the Spirits",
		["DEMONHUNTER"] = "The Hunt",
		["EVOKER"] = "Boon of the Covenants",
	},
	["Venthyr"] = {
		["SHAMAN"] = "Chain Harvest",
		["MAGE"] = "Mirrors of Torment",
		["WARLOCK"] = "Impending Catastrophe",
		["MONK"] = "Fallen Order",
		["PALADIN"] = "Ashen Hallow",
		["HUNTER"] = "Flayed Shot",
		["ROGUE"] = "Flagellation",
		["PRIEST"] = "Mindgames",
		["DEATHKNIGHT"] = "Swarming Mist",
		["WARRIOR"] = "Condemn",
		["DRUID"] = "Ravenous Frenzy",
		["DEMONHUNTER"] = "Sinful Brand",
		["EVOKER"] = "Boon of the Covenants",
	},
	["Mawsworn"] = {
		["SHAMAN"] = "",
		["MAGE"] = "",
		["WARLOCK"] = "",
		["MONK"] = "",
		["PALADIN"] = "",
		["HUNTER"] = "",
		["ROGUE"] = "",
		["PRIEST"] = "",
		["DEATHKNIGHT"] = "",
		["WARRIOR"] = "",
		["DRUID"] = "",
		["DEMONHUNTER"] = "",
		["EVOKER"] = "",
	},
	["Enlightened"] = {
		["SHAMAN"] = "",
		["MAGE"] = "",
		["WARLOCK"] = "",
		["MONK"] = "",
		["PALADIN"] = "",
		["HUNTER"] = "",
		["ROGUE"] = "",
		["PRIEST"] = "",
		["DEATHKNIGHT"] = "",
		["WARRIOR"] = "",
		["DRUID"] = "",
		["DEMONHUNTER"] = "",
		["EVOKER"] = "",
	},
}

-- uses covEnum	
ZA.covToys = {
	[0] = {""},
	[1] = {"Steward's First Feather"},
	[2] = {"Rapid Recitation Quill"},
	[3] = {"Spring Florist's Pouch\n/use Seed of Renewed Souls"},
	[4] = {"Regenerating Slime Vial"},
	[5] = {"Box of Rattling Chains"},
	[6] = {"Blue-Covered Beanbag\n/use Sphere of Enlightened Cogitation"},
}

-- Target BG Healers and Set BG Healers // Helpful measures in non-bg areas
ZA.numaltbuff101112 = {
	["SHAMAN"] = "Hex",
	["MAGE"] = "Polymorph",
	["WARLOCK"] = "Command Demon",
	["MONK"] = "Paralysis",
	["PALADIN"] = "Repentance",
	["HUNTER"] = "Intimidation",
	["ROGUE"] = "Blind",
	["PRIEST"] = "Fade",
	["DEATHKNIGHT"] = "Asphyxiate",
	["WARRIOR"] = "Storm Bolt",
	["DRUID"] = "Cyclone", 
	["DEMONHUNTER"] = "Imprison",
	["EVOKER"] = "Sleep Walk",
}
ZA.numctrlbuff101112 = {
	["SHAMAN"] = "Purge",
	["MAGE"] = "Spellsteal",
	["WARLOCK"] = "Command Demon",
	["MONK"] = "Disable",
	["PALADIN"] = "Blessing of Protection",
	["HUNTER"] = "Harpoon",
	["ROGUE"] = "Shadowstep",
	["PRIEST"] = "Leap of Faith",
	["DEATHKNIGHT"] = "Dark Simulacrum",
	["WARRIOR"] = "Charge",
	["DRUID"] = "Entangling Roots", 
	["DEMONHUNTER"] = "Consume Magic",
	["EVOKER"] = "Unravel",
}
ZA.numnomodbuff101112 = {
	["SHAMAN"] = "Water Walking",
	["MAGE"] = "Slow Fall",
	["WARLOCK"] = "Unending Breath",
	["MONK"] = "Tiger's Lust",
	["PALADIN"] = "Blessing of Freedom",
	["HUNTER"] = "Master's Call",
	["ROGUE"] = "Shadowstep",
	["PRIEST"] = "Power Infusion",
	["DEATHKNIGHT"] = "Mind Freeze",
	["WARRIOR"] = "Intervene",
	["DRUID"] = "Wild Charge", 
	["DEMONHUNTER"] = "Disrupt",
	["EVOKER"] = "Time Dilation",
}
-- Target BG Healers and Set BG Healers // Helpful measures in non-bg areas
ZA.numaltbuff789 = {
	["SHAMAN"] = "Hex",
	["MAGE"] = "Polymorph",
	["WARLOCK"] = "Command Demon",
	["MONK"] = "Paralysis",
	["PALADIN"] = "Repentance",
	["HUNTER"] = "Intimidation",
	["ROGUE"] = "Blind",
	["PRIEST"] = "Rapture",
	["DEATHKNIGHT"] = "Asphyxiate",
	["WARRIOR"] = "Storm Bolt",
	["DRUID"] = "Cyclone", 
	["DEMONHUNTER"] = "Imprison",
	["EVOKER"] = "Sleep Walk",
}
ZA.numctrlbuff789 = {
	["SHAMAN"] = "Purge",
	["MAGE"] = "Spellsteal",
	["WARLOCK"] = "Command Demon",
	["MONK"] = "Disable",
	["PALADIN"] = "Blessing of Protection",
	["HUNTER"] = "Harpoon",
	["ROGUE"] = "Shadowstep",
	["PRIEST"] = "Rapture",
	["DEATHKNIGHT"] = "Dark Simulacrum",
	["WARRIOR"] = "Charge",
	["DRUID"] = "Entangling Roots", 
	["DEMONHUNTER"] = "Consume Magic",
	["EVOKER"] = "Unravel",
}
ZA.numnomodbuff789 = {
	["SHAMAN"] = "Water Walking",
	["MAGE"] = "Slow Fall",
	["WARLOCK"] = "Unending Breath",
	["MONK"] = "Tiger's Lust",
	["PALADIN"] = "Blessing of Freedom",
	["HUNTER"] = "Master's Call",
	["ROGUE"] = "Shadowstep",
	["PRIEST"] = "Power Word: Radiance",
	["DEATHKNIGHT"] = "Mind Freeze",
	["WARRIOR"] = "Intervene",
	["DRUID"] = "Wild Charge", 
	["DEMONHUNTER"] = "Disrupt",
	["EVOKER"] = "Time Dilation",
}
-- Target BG Healers and Set BG Healers // Helpful measures in non-bg areas
ZA.modnumaltbuff789 = {
	["SHAMAN"] = "Lightning Shield",
	["MAGE"] = "Polymorph",
	["WARLOCK"] = "Command Demon",
	["MONK"] = "Paralysis",
	["PALADIN"] = "Repentance",
	["HUNTER"] = "Intimidation",
	["ROGUE"] = "Blind",
	["PRIEST"] = "Rapture",
	["DEATHKNIGHT"] = "Asphyxiate",
	["WARRIOR"] = "Storm Bolt",
	["DRUID"] = "Cyclone", 
	["DEMONHUNTER"] = "Imprison",
	["EVOKER"] = "Sleep Walk",
}
ZA.modnumctrlbuff789 = {
	["SHAMAN"] = "Purge",
	["MAGE"] = "Spellsteal",
	["WARLOCK"] = "Command Demon",
	["MONK"] = "Disable",
	["PALADIN"] = "Blessing of Protection",
	["HUNTER"] = "Harpoon",
	["ROGUE"] = "Shadowstep",
	["PRIEST"] = "Rapture",
	["DEATHKNIGHT"] = "Dark Simulacrum",
	["WARRIOR"] = "Charge",
	["DRUID"] = "Entangling Roots", 
	["DEMONHUNTER"] = "Consume Magic",
	["EVOKER"] = "Unravel",
}
ZA.modnumnomodbuff789 = {
	["SHAMAN"] = "Water Walking",
	["MAGE"] = "Slow Fall",
	["WARLOCK"] = "Unending Breath",
	["MONK"] = "Tiger's Lust",
	["PALADIN"] = "Blessing of Freedom",
	["HUNTER"] = "Master's Call",
	["ROGUE"] = "Shadowstep",
	["PRIEST"] = "Rapture",
	["DEATHKNIGHT"] = "Mind Freeze",
	["WARRIOR"] = "Intervene",
	["DRUID"] = "Wild Charge", 
	["DEMONHUNTER"] = "Disrupt",
	["EVOKER"] = "Time Dilation",
}
-- array med klass abilities för varje klass, aC == Alt+456 Class ability
	-- Helpful Dispel Array ctrl+alt+num456, borde vara helpful utility
ZA.aC = {
	["SHAMAN"] = "Cleanse Spirit",
	["MAGE"] = "Remove Curse",
	["WARLOCK"] = "Singe Magic",
	["MONK"] = "Detox",
	["PALADIN"] = "Cleanse",
	["HUNTER"] = "Roar of Sacrifice",
	["ROGUE"] = "Tricks of the Trade",
	["PRIEST"] = "Void Shift",
	["DEATHKNIGHT"] = "Chains of Ice",
	["WARRIOR"] = "Intervene",
	["DRUID"] = "Remove Corruption", 
	["DEMONHUNTER"] = "Silver-Plated Turkey Shooter",
	["EVOKER"] = "Naturalize",
}
-- array med klass abilities för varje klass, PoA == Party or Arena

ZA.arenaDots = {
	["SHAMAN"] = "Flame Shock",
	["MAGE"] = "Mage Bomb",
	["WARLOCK"] = "Singe Magic",
	["MONK"] = "Detox",
	["PALADIN"] = "Cleanse",
	["HUNTER"] = "Roar of Sacrifice",
	["ROGUE"] = "Tricks of the Trade",
	["PRIEST"] = "Shadow Word: Pain",
	["DEATHKNIGHT"] = "Outbreak",
	["WARRIOR"] = "Rend",
	["DRUID"] = "Moonfire", 
	["DEMONHUNTER"] = "Throw Glaive",
	["EVOKER"] = "Pyre",
}
ZA.altArenaDots = {
	["SHAMAN"] = "Flame Shock",
	["MAGE"] = "Mage Bomb",
	["WARLOCK"] = "Singe Magic",
	["MONK"] = "Detox",
	["PALADIN"] = "Cleanse",
	["HUNTER"] = "Roar of Sacrifice",
	["ROGUE"] = "Tricks of the Trade",
	["PRIEST"] = "Shadow Word: Death",
	["DEATHKNIGHT"] = "Outbreak",
	["WARRIOR"] = "Rend",
	["DRUID"] = "Moonfire", 
	["DEMONHUNTER"] = "Throw Glaive",
	["EVOKER"] = "Pyre",
}
ZA.ctrlArenaDots = {
	["SHAMAN"] = "Flame Shock",
	["MAGE"] = "Mage Bomb",
	["WARLOCK"] = "Singe Magic",
	["MONK"] = "Detox",
	["PALADIN"] = "Cleanse",
	["HUNTER"] = "Roar of Sacrifice",
	["ROGUE"] = "Tricks of the Trade",
	["PRIEST"] = "Penance",
	["DEATHKNIGHT"] = "Outbreak",
	["WARRIOR"] = "Rend",
	["DRUID"] = "Moonfire", 
	["DEMONHUNTER"] = "Throw Glaive",
	["EVOKER"] = "Pyre",
}
-- Offensive Counter abilities Array 
-- shift+alt+wmp456
ZA.wmpaltpurge = {
	["SHAMAN"] = "Purge",
	["MAGE"] = "Spellsteal",
	["WARLOCK"] = "Devour Magic",
	["MONK"] = "Disable",
	["PALADIN"] = "Hammer of Justice",
	["HUNTER"] = "Harpoon",
	["ROGUE"] = "Shadowstep",
	["PRIEST"] = "Dispel Magic",
	["DEATHKNIGHT"] = "Dark Simulacrum",
	["WARRIOR"] = "Charge",
	["DRUID"] = "Soothe", 
	["DEMONHUNTER"] = "Consume Magic",
	["EVOKER"] = "Unravel",
}
-- shift+ctrl+wmp456
ZA.wmpctrlcc = {
	["SHAMAN"] = "Hex",
	["MAGE"] = "Polymorph",
	["WARLOCK"] = "Fear",
	["MONK"] = "Paralysis",
	["PALADIN"] = "Repentance",
	["HUNTER"] = "Intimidation",
	["ROGUE"] = "Blind",
	["PRIEST"] = "Mind Control",
	["DEATHKNIGHT"] = "Asphyxiate",
	["WARRIOR"] = "Storm Bolt",
	["DRUID"] = "Cyclone", 
	["DEMONHUNTER"] = "Imprison",
	["EVOKER"] = "Sleep Walk",
}
ZA.wmpnomodkick = {
	["SHAMAN"] = "Wind Shear",
	["MAGE"] = "Counterspell",
	["WARLOCK"] = "Command Demon",
	["MONK"] = "Spear Hand Strike",
	["PALADIN"] = "Rebuke",
	["HUNTER"] = "Counter Shot",
	["ROGUE"] = "Kick",
	["PRIEST"] = "Silence",
	["DEATHKNIGHT"] = "Mind Freeze",
	["WARRIOR"] = "Pummel",
	["DRUID"] = "Solar Beam", 
	["DEMONHUNTER"] = "Disrupt",
	["EVOKER"] = "Quell",
}